Repository ynput/ayon-openrv, pull requests merged in 2025-05, with the labels that each got.

#42 Console interpreter: Fix import from ayon-core
  client/ayon_openrv/startup/pkgs_source/ayon_scripteditor/ayon_scripteditor.py
Labels: type: bug

#43 Remove OpenPype and avalon references
  client/ayon_openrv/api/pipeline.py
  client/ayon_openrv/api/review.py
  client/ayon_openrv/hooks/pre_ftrackdata.py
  client/ayon_openrv/hooks/pre_setup_openrv.py
  client/ayon_openrv/plugins/create/create_workfile.py
  client/ayon_openrv/plugins/load/openrv/load_frames.py
  client/ayon_openrv/plugins/load/openrv/load_mov.py
  client/ayon_openrv/startup/pkgs_source/ayon_menus/ayon_menus.py
  client/ayon_openrv/startup/pkgs_source/comments/comments.py
Labels: type: enhancement, bump minor

#47 Adds type stubs for OpenRV API
  client/ayon_openrv/py.typed
  client/ayon_openrv/typing/README.md
  client/ayon_openrv/typing/__init__.py
  client/ayon_openrv/typing/py.typed
  client/ayon_openrv/typing/rv/__init__.py
  client/ayon_openrv/typing/rv/commands/__init__.py
  client/ayon_openrv/typing/rv/extra_commands/__init__.py
  client/ayon_openrv/typing/rv/qtutils/__init__.py
  client/ayon_openrv/typing/rv/rvtypes/__init__.py
Labels: type: enhancement
