Repository ynput/ayon-openrv, pull requests merged in 2025-03, with the labels that each got.

#37 Fix and simplify sequence loading
  client/ayon_openrv/plugins/load/openrv/load_frames.py
Labels: type: bug, sponsored

#40 Load Mov: Remove usage of `self.fname`
  client/ayon_openrv/plugins/load/openrv/load_mov.py
Labels: type: enhancement, community

#41 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
